# Generated by Django 2.1.1 on 2020-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20200701_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Retired', 'Retired')], default='Prospect', max_length=10),
        ),
    ]
