# Generated by Django 2.1.1 on 2020-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='m2_total',
            field=models.IntegerField(default=0),
        ),
    ]
