# Generated by Django 3.1.2 on 2020-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Россия', 'Россия')], default='Россия', max_length=100),
        ),
    ]
