# Generated by Django 2.1.1 on 2020-06-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_m2_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
