# Generated by Django 2.1.1 on 2020-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.CharField(default='', max_length=100),
        ),
    ]
