# Generated by Django 2.1.1 on 2020-06-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200628_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuecategory',
            options={'verbose_name_plural': 'Revenue Categories'},
        ),
    ]
