# Generated by Django 2.1.1 on 2020-06-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200628_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.RevenueCategory'),
        ),
    ]
