# Generated by Django 2.1.1 on 2020-06-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200628_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
