# Generated by Django 2.1.1 on 2020-06-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200628_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.ExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.RevenueCategory'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
