# Generated by Django 3.1.2 on 2021-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200628_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('O', 'Operations'), ('I', 'Investments')], default='O', max_length=1),
        ),
    ]
